plugins {
    id 'com.android.application'
}

android {
    namespace 'shop.kwix.app'
    compileSdk 34

    defaultConfig {
        applicationId "shop.kwix.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        // Change the website address here if it ever changes.
        buildConfigField "String", "SITE", "\"https://kwix.shop\""
    }
    buildFeatures { buildConfig true }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
